name: Python Workflow for assignment #11
on: [push]
jobs:
  test:
    name: Test Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10 
        uses: actions/setup-python@v3
        with: 
          python-version: "3.10"

      - name: Run tests
        run: python3 find_lowest_number.py "test_data/test1_input.txt" "outputs/output1.txt"
